[pytest]
pythonpath = .
filterwarnings =
    ignore::DeprecationWarning:_yaml
    ignore:ast.Str is deprecated and will be removed in Python 3.14; use ast.Constant instead:DeprecationWarning:metaflow\.graph
    ignore:Attribute s is deprecated and will be removed in Python 3.14; use value instead:DeprecationWarning:metaflow\.graph
    ignore:The resulting number of chunks is too low\.:UserWarning:nannyml\.chunk
