artifact_location: file:///Users/shlomibenshushan/Repositories/OU-22971-Toolbox/MLOps/04_mlflow_logging/mlflow_tracking/828001045686934645
creation_time: 1773504165628
experiment_id: '828001045686934645'
last_update_time: 1773504165628
lifecycle_stage: active
name: 04_mlflow_logging
workspace: default
